services:
  mongodb:
    image: mongo:7
    container_name: warframe-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: warframe
    networks:
      - warframe-wishlist

  api:
    build: .
    container_name: warframe-api
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
      - SERVER_PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE=warframe
      - SUPABASE_URL=https://lpqitpotjqilkjupjrby.supabase.co
      - SUPABASE_JWT_PUBLIC_KEY={"x":"Jbyx6pk671geFSLcGAmjuLOw2ShrQI6ssuFzbU68ghM","y":"UcyftzYqV5oQUR1kd7Wmc7A16TENIRHhcs5LsDAjt-g","alg":"ES256","crv":"P-256","ext":true,"kid":"db204d5b-ac12-42a3-a2a1-3659f50ba96b","kty":"EC","key_ops":["verify"]}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - warframe-wishlist
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build: ./web
    container_name: warframe-web
    ports:
      - "3000:80"
    environment:
      - VITE_SUPABASE_URL=https://lpqitpotjqilkjupjrby.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcWl0cG90anFpbGtqdXBqcmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NDcyMTgsImV4cCI6MjA4NTEyMzIxOH0.5kA5NRFbf4O3X1mdV6Qf98m3Poa5nF3QjMmTZLo3JHw
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - warframe-wishlist

networks:
  warframe-wishlist:
    driver: bridge

volumes:
  mongodb_data:
