apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warframe-wishlist.fullname" . }}
  labels:
    {{- include "warframe-wishlist.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}
  MONGO_DATABASE: {{ .Values.mongodb.database | quote }}
  {{- if .Values.supabase.url }}
  SUPABASE_URL: {{ .Values.supabase.url | quote }}
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  # Internal MongoDB host (service name)
  MONGO_HOST: {{ include "warframe-wishlist.fullname" . }}-mongodb
  {{- end }}
